[package]
name = "provider-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
domain = { workspace = true }
feed-rs = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
url = { workspace = true }
thiserror = { workspace = true }
base64 = { workspace = true }
reader = { workspace = true }
scraper = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
